services:
  - type: web
    name: tukuntech-back
    runtime: docker
    plan: free
    branch: feature/deploy
    autoDeploy: true

    # (opcional si tu Dockerfile está en la raíz)
    dockerfilePath: Dockerfile
    dockerContext: .

    # health check para zero-downtime
    healthCheckPath: /api/v1/actuator/health

    # envs no secretas aquí; los secretos los cargamos en el panel
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CORS_ALLOWED_ORIGINS
        value: http://localhost:4200
