spring:
  application:
    name: tukuntech-backend

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: ${DB_POOL_MAX:10}
      minimum-idle: ${DB_POOL_MIN:2}
      connection-timeout: ${DB_CONN_TIMEOUT_MS:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT_MS:600000}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL:update}
    show-sql: ${JPA_SHOW_SQL:true}
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

server:
  port: ${PORT:${SERVER_PORT:8080}}
  servlet:
    context-path: /api/v1


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:4200}
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

app:
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: tukuntech-api
      access-token-expiration: ${JWT_ACCESS_EXPIRATION:1800000}
      refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:1209600000}
      maximum-sessions: ${JWT_MAX_SESSIONS:5}
  seed:
    enabled: ${APP_SEED_ENABLED:false}


